[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "agid_assessment_methodology"
version = "0.1.0"
description = "A comprehensive security audit framework for ABSC minimum security measures implementation. This system provides automated security checks, compliance verification, reporting, and scheduling capabilities for IT infrastructure security assessment. It features modular architecture supporting Windows and Linux environments, with built-in checks for device inventory, vulnerability management, malware protection, authentication policies, backup procedures, encryption, and logging practices. Results are stored in SQLite/PostgreSQL and can be exported in multiple formats (JSON, CSV, HTML, PDF). The framework includes a full CLI interface, with planned web UI and REST API support."
readme = "README.rst"
authors = [
  {name = "Caterina Ianeselli", email = "ianesellicaterina@gmail.com"}
]
maintainers = [
  {name = "Caterina Ianeselli", email = "ianesellicaterina@gmail.com"}
]
classifiers = [

]
license = {text = "GNU General Public License v3"}
dependencies = [
  
]

[project.optional-dependencies]
dev = [
    "coverage",  # testing
    "mypy",  # linting
    "pytest",  # testing
    "ruff"  # linting
]

[project.urls]

bugs = "https://github.com/icate95/agid_assessment_methodology/issues"
changelog = "https://github.com/icate95/agid_assessment_methodology/blob/master/changelog.md"
homepage = "https://github.com/icate95/agid_assessment_methodology"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
"*" = ["*.*"]




# Mypy
# ----

[tool.mypy]
files = "."

# Use strict defaults
strict = true
warn_unreachable = true
warn_no_return = true

[[tool.mypy.overrides]]
# Don't require test functions to include types
module = "tests.*"
allow_untyped_defs = true
disable_error_code = "attr-defined"

